(()=>{
const PLANS={
mon:{title:'Понедельник',subtitle:'Front Lever · основной день',load:'ОСНОВНОЙ ДЕНЬ',ex:[['Tuck Front Lever','3 × 5–10 сек','Элемент','2–3 мин'],['Подъёмы в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Front Lever с резинкой','3 × 5–10 сек','Элемент','2–3 мин'],['Подтягивания в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
tue:{title:'Вторник',subtitle:'База',load:'БАЗА',ex:[['Чистые подтягивания','3 × 6','Сила','60–90 сек'],['Отжимания на брусьях','3 × 3–4','Сила','60–90 сек'],['Tuck Front Lever','2 × 5–10 сек','Элемент','2–3 мин'],['Высокие подтягивания','2 × 2–3','Мощность','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
wed:{title:'Среда',subtitle:'Front Lever · основной день',load:'ОСНОВНОЙ ДЕНЬ',ex:[['Tuck Front Lever','3 × 5–10 сек','Элемент','2–3 мин'],['Подъёмы в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Front Lever с резинкой','3 × 5–10 сек','Элемент','2–3 мин'],['Подтягивания в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
thu:{title:'Четверг',subtitle:'Лёгкая тренировка',load:'ЛЁГКИЙ ДЕНЬ',ex:[['Tuck Front Lever','2 × 5–8 сек легко','Элемент','2–3 мин'],['Front Lever с сильной резинкой','2 × 5–8 сек легко','Элемент','2–3 мин'],['Лёгкие подтягивания','2 × 5','Техника','60–90 сек'],['Высокие подтягивания','2 × 2 легко','Мощность','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
fri:{title:'Пятница',subtitle:'Front Lever · основной день',load:'ОСНОВНОЙ ДЕНЬ',ex:[['Tuck Front Lever','3 × 5–10 сек','Элемент','2–3 мин'],['Подъёмы в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Front Lever с резинкой','3 × 5–10 сек','Элемент','2–3 мин'],['Подтягивания в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
sat:{title:'Суббота',subtitle:'База',load:'БАЗА',ex:[['Чистые подтягивания','3 × 6','Сила','60–90 сек'],['Отжимания на брусьях','3 × 3–4','Сила','60–90 сек'],['Tuck Front Lever','2 × 5–10 сек','Элемент','2–3 мин'],['Высокие подтягивания','2 × 2–3','Мощность','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
sun:{title:'Воскресенье',subtitle:'Умеренная нагрузка',load:'УМЕРЕННО',ex:[['Tuck Front Lever','2 × 5–10 сек','Элемент','2–3 мин'],['Front Lever с резинкой','2 × 5–10 сек','Элемент','2–3 мин'],['Чистые подтягивания','2 × 5','Сила','60–90 сек'],['Высокие подтягивания','2 × 2–3','Мощность','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]}
};
const DAYS=[['mon','ПН'],['tue','ВТ'],['wed','СР'],['thu','ЧТ'],['fri','ПТ'],['sat','СБ'],['sun','ВС']],today=()=>DAYS[(new Date().getDay()+6)%7][0];
const monday=()=>{const d=new Date();d.setHours(0,0,0,0);const n=d.getDay()||7;d.setDate(d.getDate()-n+1);return d},dateFor=i=>{const d=monday();d.setDate(d.getDate()+i);return d};
const k=(d,i)=>`frontlever:${d}:${i}`,sk=(d,i,s)=>`${k(d,i)}:set:${s}`,uk=(d,i)=>`${k(d,i)}:unit`;
function cfg(ex){if(ex[0].includes('Уголок'))return{count:2,unit:'сек'};const m=ex[1].match(/^(\d+)\s*×/);return{count:m?+m[1]:1,unit:ex[1].includes('сек')?'сек':'повт.'}}
function build(){const view=document.getElementById('frontleverView');if(!view)return;view.innerHTML=`<article class="poster-card"><img src="./front-lever.png?v=27" alt="Передний вис" fetchpriority="high" decoding="async"><div class="poster-glow"></div><div class="poster-bottom"><span class="pill">ПРОГРЕСС ЗА НЕДЕЛЮ</span><div class="poster-row"><div><h2>Передний вис</h2><p>Выполнение тренировочного плана за выбранную неделю</p></div><strong id="flWeekPct">0%</strong></div><div class="progress-track"><div id="flWeekBar" class="progress-fill"></div></div></div></article><section class="week-section" id="flWeek"><div class="section-head"><div><span class="mini">ЭТА НЕДЕЛЯ</span><h3 id="flWeekLabel"></h3></div></div><div id="flDays" class="day-strip"></div><article class="workout-panel"><div class="workout-heading"><div><span id="flLoad" class="load-badge"></span><h3 id="flTitle"></h3><p id="flSub"></p></div><div class="day-score"><strong id="flPct">0%</strong><span>готово</span></div></div><div id="flList" class="exercise-list"></div><div class="day-progress-footer"><div class="progress-track"><div id="flBar" class="progress-fill"></div></div><p id="flProgressText"></p></div></article></section><article class="safety"><b>⚡ Главное — техника.</b><span> Боль в локте, плече или запястье — останови раздражающее упражнение и дай восстановиться.</span></article>`;
let selected=today(),open=null;const mon=monday(),sun=dateFor(6);document.getElementById('flWeekLabel').textContent=`${mon.toLocaleDateString('ru-RU',{day:'numeric',month:'short'})} — ${sun.toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}`;
function progress(){const p=PLANS[selected],done=p.ex.filter((_,i)=>localStorage.getItem(k(selected,i))==='1').length,pct=Math.round(done/p.ex.length*100);document.getElementById('flPct').textContent=pct+'%';document.getElementById('flBar').style.width=pct+'%';document.getElementById('flProgressText').textContent=`${done} из ${p.ex.length} упражнений выполнено`;let a=0,t=0;DAYS.forEach(([d])=>PLANS[d].ex.forEach((_,i)=>{t++;if(localStorage.getItem(k(d,i))==='1')a++}));const w=Math.round(a/t*100);document.getElementById('flWeekPct').textContent=w+'%';document.getElementById('flWeekBar').style.width=w+'%'}
function render(){const strip=document.getElementById('flDays');strip.innerHTML='';DAYS.forEach(([d,label],i)=>{const b=document.createElement('button');b.type='button';b.className='day-btn'+(d===selected?' active':'');b.innerHTML=`<span class="dname">${label}</span><span class="dnum">${dateFor(i).getDate()}</span>`;b.onclick=()=>{selected=d;open=null;render()};strip.appendChild(b)});const p=PLANS[selected];document.getElementById('flLoad').textContent=p.load;document.getElementById('flTitle').textContent=p.title;document.getElementById('flSub').textContent=p.subtitle;const list=document.getElementById('flList');list.innerHTML='';p.ex.forEach((ex,i)=>{const id=k(selected,i),done=localStorage.getItem(id)==='1',c=cfg(ex),unit=localStorage.getItem(uk(selected,i))||c.unit,card=document.createElement('article');card.className='exercise-card'+(done?' checked':'')+(open===id?' exercise-open':'');const fields=Array.from({length:c.count},(_,s)=>`<label class="set-field"><span>Подход ${s+1}</span><span class="set-input-wrap"><input class="set-input" type="number" inputmode="decimal" min="0" max="9999" step="0.1" value="${localStorage.getItem(sk(selected,i,s))||''}" placeholder="—" data-set="${s}"></span></label>`).join('');card.innerHTML=`<div class="exercise-top" role="button" tabindex="0" aria-expanded="${open===id}"><button class="exercise-check" type="button"><span class="check-box">${done?'✓':''}</span></button><span class="exercise-main"><b>${ex[0]}</b><span>${ex[1]} · Отдых: ${ex[3]}</span></span><span class="exercise-chevron">${open===id?'⌃':'⌄'}</span></div><div class="exercise-details"><div class="result-toolbar"><span>Записать результат</span><label>Единица <select class="unit-select"><option value="повт."${unit==='повт.'?' selected':''}>повт.</option><option value="сек"${unit==='сек'?' selected':''}>сек</option></select></label></div><div class="set-results">${fields}</div></div>`;card.querySelector('.exercise-top').onclick=e=>{if(e.target.closest('.exercise-check'))return;open=open===id?null:id;render()};card.querySelector('.exercise-check').onclick=e=>{e.stopPropagation();localStorage.setItem(id,done?'0':'1');render()};card.querySelector('.unit-select').onchange=e=>localStorage.setItem(uk(selected,i),e.target.value);card.querySelectorAll('.set-input').forEach(inp=>inp.oninput=()=>localStorage.setItem(sk(selected,i,+inp.dataset.set),inp.value));list.appendChild(card)});progress()}
render();window.openFrontLeverToday=()=>{selected=today();open=null;render();setTimeout(()=>document.getElementById('flWeek')?.scrollIntoView({behavior:'smooth',block:'start'}),80)};}
setTimeout(build,40);
})();