(()=>{
const PLANS={
mon:{title:'Понедельник',subtitle:'Основной · Front Lever',ex:[['Tuck Front Lever','3 × 5–10 сек','Элемент','2–3 мин'],['Подъёмы в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Front Lever с резинкой','3 × 5–10 сек','Элемент','2–3 мин'],['Подтягивания в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
tue:{title:'Вторник',subtitle:'База',ex:[['Чистые подтягивания','3 × 6','Сила','60–90 сек'],['Отжимания на брусьях','3 × 3–4','Сила','60–90 сек'],['Tuck Front Lever','2 × 5–10 сек','Элемент','2–3 мин'],['Высокие подтягивания','2 × 2–3','Мощность','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
wed:{title:'Среда',subtitle:'Основной · Front Lever',ex:[['Tuck Front Lever','3 × 5–10 сек','Элемент','2–3 мин'],['Подъёмы в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Front Lever с резинкой','3 × 5–10 сек','Элемент','2–3 мин'],['Подтягивания в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
thu:{title:'Четверг',subtitle:'Лёгкий',ex:[['Tuck Front Lever','2 × 5–8 сек легко','Элемент','2–3 мин'],['Front Lever с сильной резинкой','2 × 5–8 сек легко','Элемент','2–3 мин'],['Лёгкие подтягивания','2 × 5','Техника','60–90 сек'],['Высокие подтягивания','2 × 2 легко','Мощность','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
fri:{title:'Пятница',subtitle:'Основной · Front Lever',ex:[['Tuck Front Lever','3 × 5–10 сек','Элемент','2–3 мин'],['Подъёмы в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Front Lever с резинкой','3 × 5–10 сек','Элемент','2–3 мин'],['Подтягивания в Tuck Front Lever','3 × 3–5','Сила','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
sat:{title:'Суббота',subtitle:'База',ex:[['Чистые подтягивания','3 × 6','Сила','60–90 сек'],['Отжимания на брусьях','3 × 3–4','Сила','60–90 сек'],['Tuck Front Lever','2 × 5–10 сек','Элемент','2–3 мин'],['Высокие подтягивания','2 × 2–3','Мощность','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]},
sun:{title:'Воскресенье',subtitle:'Умеренный',ex:[['Tuck Front Lever','2 × 5–10 сек','Элемент','2–3 мин'],['Front Lever с резинкой','2 × 5–10 сек','Элемент','2–3 мин'],['Чистые подтягивания','2 × 5','Сила','60–90 сек'],['Высокие подтягивания','2 × 2–3','Мощность','2–3 мин'],['Уголок','2 подхода','Кор','45–60 сек'],['Финиш: выход силой','2 × 2','Финиш','2–3 мин']]}
};
const days=[['mon','ПН'],['tue','ВТ'],['wed','СР'],['thu','ЧТ'],['fri','ПТ'],['sat','СБ'],['sun','ВС']];
const today=()=>days[(new Date().getDay()+6)%7][0];
const key=(d,i)=>`frontlever:${d}:${i}`,setKey=(d,i,s)=>`${key(d,i)}:set:${s}`;
function sets(label){const m=label.match(/^(\d+)\s*×/);return m?+m[1]:2}
function build(){const v=document.getElementById('frontleverView');if(!v)return;v.innerHTML=`<article class="poster-card"><img src="./front-lever.png?v=27" alt="Передний вис" fetchpriority="high" decoding="async"><div class="poster-glow"></div><div class="poster-bottom"><span class="pill">ТЕКУЩАЯ ЦЕЛЬ</span><div class="poster-row"><div><h2>Передний вис</h2><p>Сила спины, прямых рук и корпуса</p></div><strong id="flWeekPercent">0%</strong></div><div class="progress-track"><div id="flWeekBar" class="progress-fill"></div></div></div></article><section class="week-section fl-week"><div class="section-head"><div><span class="mini">ЭТА НЕДЕЛЯ</span><h3>Программа Front Lever</h3></div></div><div id="flDays" class="day-strip"></div><article class="workout-panel"><div class="workout-heading"><div><span id="flBadge" class="load-badge">Тренировка</span><h3 id="flTitle"></h3><p id="flSub"></p></div><div class="day-score"><strong id="flPct">0%</strong><span>готово</span></div></div><div id="flList" class="exercise-list"></div><div class="day-progress-footer"><div class="progress-track"><div id="flBar" class="progress-fill"></div></div><p id="flText"></p></div></article></section><article class="safety"><b>⚡ Главное — техника.</b><span> Не работай через боль в локтях, плечах или запястьях.</span></article>`;let selected=today();
const render=()=>{document.querySelectorAll('#flDays .day-btn').forEach(b=>b.classList.toggle('active',b.dataset.day===selected));const p=PLANS[selected];document.getElementById('flTitle').textContent=p.title;document.getElementById('flSub').textContent=p.subtitle;document.getElementById('flBadge').textContent=p.subtitle.split(' · ')[0];const list=document.getElementById('flList');list.innerHTML='';p.ex.forEach((e,i)=>{const done=localStorage.getItem(key(selected,i))==='1',card=document.createElement('article');card.className='exercise-card'+(done?' done':'');let inputs='';for(let s=0;s<sets(e[1]);s++){inputs+=`<label class="set-result"><span>${s+1}</span><input class="set-input" inputmode="decimal" placeholder="—" value="${localStorage.getItem(setKey(selected,i,s))||''}" data-i="${i}" data-s="${s}"></label>`}card.innerHTML=`<label class="exercise-check"><input type="checkbox" data-i="${i}" ${done?'checked':''}><span></span></label><div class="exercise-main"><div class="exercise-top"><div><h4>${e[0]}</h4><p>${e[1]}</p></div><span class="exercise-tag">${e[2]}</span></div><div class="exercise-meta"><span>Отдых: <b>${e[3]}</b></span></div><div class="sets-row">${inputs}</div></div>`;list.appendChild(card)});list.querySelectorAll('input[type=checkbox]').forEach(x=>x.onchange=()=>{localStorage.setItem(key(selected,+x.dataset.i),x.checked?'1':'0');render()});list.querySelectorAll('.set-input').forEach(x=>x.onchange=()=>localStorage.setItem(setKey(selected,+x.dataset.i,+x.dataset.s),x.value));progress()};
const progress=()=>{const p=PLANS[selected],done=p.ex.filter((_,i)=>localStorage.getItem(key(selected,i))==='1').length,pct=Math.round(done/p.ex.length*100);document.getElementById('flPct').textContent=pct+'%';document.getElementById('flBar').style.width=pct+'%';document.getElementById('flText').textContent=`Выполнено ${done} из ${p.ex.length}`;let all=0,total=0;days.forEach(([d])=>PLANS[d].ex.forEach((_,i)=>{total++;if(localStorage.getItem(key(d,i))==='1')all++}));const w=Math.round(all/total*100);document.getElementById('flWeekPercent').textContent=w+'%';document.getElementById('flWeekBar').style.width=w+'%'};
const strip=document.getElementById('flDays');days.forEach(([d,l])=>{const b=document.createElement('button');b.className='day-btn';b.dataset.day=d;b.innerHTML=`<b>${l}</b>`;b.onclick=()=>{selected=d;render()};strip.appendChild(b)});render();window.openFrontLeverToday=()=>{selected=today();render();setTimeout(()=>document.querySelector('#frontleverView .fl-week')?.scrollIntoView({behavior:'smooth',block:'start'}),80)};}
setTimeout(build,30);
})();