(()=>{
const K=(k,s='')=>`v33:${k}:${s}`, W=()=>typeof viewedWeek!=='undefined'?viewedWeek:new Date();
const done=(d,k)=>d[K('finished',k)]===true||(typeof dayIsDone==='function'&&dayIsDone(d,k));
function todayCard(){const key=getTodayKey(),p=PROGRAM[key],h=document.querySelector('#menuToday h2'),t=document.querySelector('#menuToday p');if(h)h.textContent=`Сегодня: ${p.exercises.length} упражнений · ~30 мин`;if(t)t.textContent='Открыть тренировку → план, подходы, отдых и результаты'}
function restSeconds(text=''){if(/по самочувствию|один подход/i.test(text))return 0;const nums=(text.match(/\d+/g)||[]).map(Number);if(!nums.length)return 0;if(/мин/i.test(text))return Math.max(...nums)*60;return Math.max(...nums)}
function startAutoRest(sec){if(!sec)return;const box=document.querySelector('.v42-tools'),btn=box?.querySelector(`.v42-times button[data-s="${sec}"]`);if(btn){btn.click();box.scrollIntoView({behavior:'smooth',block:'center'});return}window.dispatchEvent(new CustomEvent('v43-rest',{detail:{seconds:sec}}))}
function hookChecks(){document.querySelectorAll('.exercise-card').forEach((card,i)=>{const b=card.querySelector('.exercise-check');if(!b||b.dataset.v43)return;b.dataset.v43='1';b.addEventListener('click',()=>{setTimeout(()=>{if(card.classList.contains('checked'))startAutoRest(restSeconds(PROGRAM[selectedDay]?.exercises[i]?.[3]))},80)})})}
function weekStats(date=W()){const d=getWeekData(date),o={days:0,sets:0,notes:0,effort:0};DAYS.forEach(([k])=>{if(done(d,k))o.days++;if((d[K('note',k)]||'').trim())o.notes++;if(d[K('effort',k)])o.effort++;PROGRAM[k].exercises.forEach((ex,i)=>{const c=setConfig(ex);for(let s=0;s<c.count;s++){const v=d[setValueId(k,i,s)];if(v!==''&&v!=null)o.sets++}})});return o}
function bandRank(x){return({'Сильная':1,'Средняя':2,'Слабая':3,'Очень слабая':4,'Без резинки':5})[x]||0}
function weakerBand(){const cur=getWeekData(W()),prev=new Date(mondayOf(W()));prev.setDate(prev.getDate()-7);const old=getWeekData(prev);let a=0,b=0;DAYS.forEach(([k])=>{a=Math.max(a,bandRank(cur[K('band',k)]));b=Math.max(b,bandRank(old[K('band',k)]))});return a>b&&b>0}
function quests(){const s=weekStats(),list=[['Три тренировки','Заверши 3 тренировки за неделю',Math.min(s.days,3),3],['Запиши результаты','Запиши результаты минимум 12 подходов',Math.min(s.sets,12),12],['Следи за ощущениями','Оцени сложность 2 тренировок',Math.min(s.effort,2),2],['Техническая заметка','Оставь заметку хотя бы к 1 тренировке',Math.min(s.notes,1),1]];return list}
function achievements(){const s=weekStats(),all=[];if(s.days>=1)all.push(['Первый шаг','Завершена тренировка']);if(s.days>=3)all.push(['Стабильность','3 тренировки за неделю']);if(s.days>=7)all.push(['Полная неделя','7 тренировок отмечены']);if(s.sets>=20)all.push(['Статистик','Записано 20 подходов']);if(weakerBand())all.push(['Меньше помощи','Использована более слабая резинка, чем на прошлой неделе']);return all}
function ensureMenu(){const actions=document.querySelector('.menu-actions');if(actions&&!document.getElementById('menuAchievements')){const b=document.createElement('button');b.id='menuAchievements';b.innerHTML='<span>★</span><b>Достижения</b><small>Задачи недели</small>';b.onclick=openGame;actions.appendChild(b)}if(actions&&!document.getElementById('menuBackup')){const b=document.createElement('button');b.id='menuBackup';b.innerHTML='<span>↓</span><b>Резервная копия</b><small>Сохранить данные</small>';b.onclick=backup;actions.appendChild(b)}}
function ensureView(){const main=document.querySelector('#trainingView main');if(!main||document.getElementById('achievementsView'))return;const v=document.createElement('section');v.id='achievementsView';v.className='view game43-view';v.innerHTML='<div class="game43-head"><span class="mini">МОЙ ПРОГРЕСС</span><h2>Достижения</h2><p>Небольшие задачи на выбранную неделю. Они не требуют тренироваться через усталость или боль.</p></div><div id="game43Mount"></div>';main.appendChild(v)}
function renderGame(){ensureView();const q=quests(),a=achievements(),m=document.getElementById('game43Mount');if(!m)return;const completed=q.filter(x=>x[2]>=x[3]).length;m.innerHTML=`<article class="game43-score"><small>ЗАДАЧИ НЕДЕЛИ</small><strong>${completed}/${q.length}</strong><span>выполнено</span></article><div class="game43-list">${q.map(x=>`<article class="game43-quest ${x[2]>=x[3]?'done':''}"><div><b>${x[2]>=x[3]?'✓ ':'○ '}${x[0]}</b><small>${x[1]}</small></div><strong>${x[2]}/${x[3]}</strong></article>`).join('')}</div><h3 class="game43-title">Полученные достижения</h3><div class="game43-badges">${a.length?a.map(x=>`<article><span>★</span><b>${x[0]}</b><small>${x[1]}</small></article>`).join(''):'<p>Выполняй обычные тренировки — достижения появятся здесь автоматически.</p>'}</div><article class="game43-backup"><h3>Резервная копия</h3><p>Сохрани всю локальную историю тренировок в один файл. Его можно хранить у себя и восстановить позже.</p><button id="game43Export">Создать резервную копию</button><label>Восстановить из файла<input id="game43Import" type="file" accept="application/json,.json"></label></article>`;document.getElementById('game43Export').onclick=backup;document.getElementById('game43Import').onchange=restore}
function openGame(){ensureView();document.getElementById('menuView').classList.add('hidden');document.getElementById('trainingView').classList.remove('hidden');document.querySelectorAll('#trainingView .view').forEach(v=>v.classList.remove('active'));document.getElementById('achievementsView').classList.add('active');renderGame();window.scrollTo(0,0)}
function backup(){const data={format:'calisthenics-backup-v1',created:new Date().toISOString(),items:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('week:'))data.items[k]=localStorage.getItem(k)}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`calisthenics-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function restore(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.format!=='calisthenics-backup-v1'||!d.items)throw 0;if(!confirm('Восстановить данные из этой резервной копии? Текущие недели с такими же датами будут заменены.'))return;Object.entries(d.items).forEach(([k,v])=>{if(k.startsWith('week:')&&typeof v==='string')localStorage.setItem(k,v)});alert('Данные восстановлены. Приложение сейчас обновится.');location.reload()}catch{alert('Не удалось прочитать резервную копию.')}};r.readAsText(f)}
function run(){todayCard();ensureMenu();ensureView();hookChecks();renderGame()}
if(typeof renderWeek==='function'){const base=renderWeek;renderWeek=function(...a){const r=base.apply(this,a);setTimeout(run,0);return r}}
setTimeout(run,0);
})();