(()=>{
let anchor=new Date();
const START=new Date(2026,8,1);START.setHours(0,0,0,0);
const mon=d=>{const x=new Date(d);x.setHours(0,0,0,0);const n=x.getDay()||7;x.setDate(x.getDate()-n+1);return x};
const FIRST=mon(START),key=d=>`week:${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parse=s=>{try{return JSON.parse(localStorage.getItem(s)||'{}')}catch{return{}}};
const monthName=d=>{const s=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(d).replace(' г.','');return s[0].toUpperCase()+s.slice(1)};
const range=d=>{const a=mon(d),b=new Date(a);b.setDate(b.getDate()+6);return`${a.toLocaleDateString('ru-RU',{day:'numeric',month:'short'})} — ${b.toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}`};
const clamp=()=>{const now=new Date();if(anchor>now)anchor=now;if(anchor<START)anchor=new Date(START)};
function ensure(){const view=document.getElementById('historyView');if(!view||document.getElementById('historyNav48'))return;const head=view.querySelector('.history-head'),n=document.createElement('div');n.id='historyNav48';n.className='history-nav48';n.innerHTML=`<div class="history-nav-row"><button data-m="-1">‹</button><div><small>МЕСЯЦ</small><b id="histMonth48"></b></div><button data-m="1">›</button></div><div class="history-nav-row"><button data-w="-1">‹ Неделя</button><div><small>НЕДЕЛЯ</small><b id="histWeek48"></b></div><button data-w="1">Неделя ›</button></div>`;head.insertAdjacentElement('afterend',n);n.onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.w){anchor=mon(anchor);anchor.setDate(anchor.getDate()+Number(b.dataset.w)*7)}else{const dir=Number(b.dataset.m);anchor=dir<0?new Date(anchor.getFullYear(),anchor.getMonth()-1,1):new Date(anchor.getFullYear(),anchor.getMonth()+1,1);if(dir<0&&anchor<START)anchor=new Date(START)}clamp();paint()}}
function paint(){ensure();clamp();const list=document.getElementById('historyList'),m=document.getElementById('histMonth48'),w=document.getElementById('histWeek48');if(!list||!m||!w)return;const a=mon(anchor),now=mon(new Date());m.textContent=monthName(anchor);w.textContent=range(a);const prevW=document.querySelector('#historyNav48 [data-w="-1"]'),nextW=document.querySelector('#historyNav48 [data-w="1"]'),prevM=document.querySelector('#historyNav48 [data-m="-1"]'),nextM=document.querySelector('#historyNav48 [data-m="1"]');if(prevW)prevW.disabled=a<=FIRST;if(nextW)nextW.disabled=a>=now;if(prevM)prevM.disabled=anchor.getFullYear()===START.getFullYear()&&anchor.getMonth()===START.getMonth();if(nextM)nextM.disabled=anchor.getFullYear()===new Date().getFullYear()&&anchor.getMonth()===new Date().getMonth();list.innerHTML='';const data=parse(key(a)),done=typeof countCompleted==='function'?countCompleted(data):0,total=typeof totalExercises==='function'?totalExercises():0,pct=total?Math.round(done/total*100):0,c=document.createElement('article');c.className='history-card';c.innerHTML=`<div class="history-top"><div><h3>${range(a)}</h3><p>${done} из ${total} упражнений</p></div><strong class="history-percent">${pct}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div>`;list.appendChild(c)}
const old=window.renderHistory;if(typeof old==='function')window.renderHistory=function(...x){const r=old.apply(this,x);setTimeout(paint,0);return r};
document.getElementById('menuHistory')?.addEventListener('click',()=>{anchor=new Date();setTimeout(paint,0)});setTimeout(()=>{ensure();paint()},0);
})();