(()=>{
let anchor=new Date();
const mon=d=>{const x=new Date(d);x.setHours(0,0,0,0);const n=x.getDay()||7;x.setDate(x.getDate()-n+1);return x};
const key=d=>`week:${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parse=s=>{try{return JSON.parse(localStorage.getItem(s)||'{}')}catch{return{}}};
const monthName=d=>{const s=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(d).replace(' г.','');return s[0].toUpperCase()+s.slice(1)};
const range=d=>{const a=mon(d),b=new Date(a);b.setDate(b.getDate()+6);return`${a.toLocaleDateString('ru-RU',{day:'numeric',month:'short'})} — ${b.toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}`};
function ensure(){const view=document.getElementById('historyView');if(!view||document.getElementById('historyNav48'))return;const head=view.querySelector('.history-head');const n=document.createElement('div');n.id='historyNav48';n.className='history-nav48';n.innerHTML=`<div class="history-nav-row"><button data-m="-1">‹</button><div><small>МЕСЯЦ</small><b id="histMonth48"></b></div><button data-m="1">›</button></div><div class="history-nav-row"><button data-w="-1">‹ Неделя</button><div><small>НЕДЕЛЯ</small><b id="histWeek48"></b></div><button data-w="1">Неделя ›</button></div>`;head.insertAdjacentElement('afterend',n);n.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.w){anchor=mon(anchor);anchor.setDate(anchor.getDate()+Number(b.dataset.w)*7)}else if(b.dataset.m){anchor=new Date(anchor.getFullYear(),anchor.getMonth()+Number(b.dataset.m),15)}if(anchor>new Date())anchor=new Date();paint()}}
function paint(){ensure();const list=document.getElementById('historyList'),m=document.getElementById('histMonth48'),w=document.getElementById('histWeek48');if(!list||!m||!w)return;m.textContent=monthName(anchor);w.textContent=range(anchor);const now=mon(new Date()),a=mon(anchor);document.querySelectorAll('#historyNav48 button[data-w="1"],#historyNav48 button[data-m="1"]').forEach(b=>b.disabled=(b.dataset.w&&a>=now)||(b.dataset.m&&anchor.getFullYear()===new Date().getFullYear()&&anchor.getMonth()>=new Date().getMonth()));list.innerHTML='';let any=false;for(let i=0;i<5;i++){const d=mon(anchor);d.setDate(d.getDate()-i*7);if(d.getMonth()!==anchor.getMonth()&&i>0)continue;const data=parse(key(d)),done=typeof countCompleted==='function'?countCompleted(data):0,total=typeof totalExercises==='function'?totalExercises():0,pct=total?Math.round(done/total*100):0;const c=document.createElement('article');c.className='history-card';c.innerHTML=`<div class="history-top"><div><h3>${range(d)}</h3><p>${done} из ${total} упражнений</p></div><strong class="history-percent">${pct}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div>`;list.appendChild(c);any=true}if(!any)list.innerHTML='<div class="empty-history">За этот месяц пока нет недель.</div>'}
const old=window.renderHistory;if(typeof old==='function')window.renderHistory=function(...x){const r=old.apply(this,x);setTimeout(paint,0);return r};
document.getElementById('menuHistory')?.addEventListener('click',()=>{anchor=new Date();setTimeout(paint,0)});
setTimeout(()=>{ensure();paint()},0);
})();