(()=>{
const BANDS=['Не указана','Сильная','Средняя','Слабая','Без резинки'];
const METRICS=[['muscle','Выход силой'],['pull','Подтягивания'],['dip','Брусья'],['lsit','Уголок']];
const dayIdx=k=>DAYS.findIndex(x=>x[0]===k);
const dateLabel=d=>d.toLocaleDateString('ru-RU',{day:'numeric',month:'short'});
const wk=()=>typeof viewedWeek!=='undefined'?viewedWeek:new Date();
function extraKey(k,s=''){return`v33:${k}:${s}`}
function data(){return getWeekData(wk())}
function save(d){saveWeekData(d,wk())}
function dayFinished(d,k){return d[extraKey('finished',k)]===true||(typeof dayIsDone==='function'&&dayIsDone(d,k))}
function resultValues(d,k,i){const cfg=setConfig(PROGRAM[k].exercises[i]);return Array.from({length:cfg.count},(_,s)=>Number(d[setValueId(k,i,s)])).filter(Number.isFinite).filter(v=>v>=0)}
function classify(name){if(name.includes('Выход силой'))return'muscle';if(name.includes('брусьях'))return'dip';if(name.includes('Уголок'))return'lsit';if(name.includes('подтягиван')||name.includes('Подтягиван'))return'pull';return null}
function weekMetrics(date){const d=getWeekData(date),out={muscle:0,pull:0,dip:0,lsit:0,finished:0,sets:0};DAYS.forEach(([k])=>{if(d[extraKey('finished',k)]===true||dayIsDone(d,k))out.finished++;PROGRAM[k].exercises.forEach((ex,i)=>{const type=classify(ex[0]);if(!type)return;const vals=resultValues(d,k,i);if(vals.length){out[type]=Math.max(out[type],...vals);out.sets+=vals.length}})});return out}
function recentWeeks(n=8){const base=mondayOf(wk()),arr=[];for(let i=n-1;i>=0;i--){const d=new Date(base);d.setDate(d.getDate()-i*7);arr.push({date:d,m:weekMetrics(d)})}return arr}
function records(){const rec={muscle:null,pull:null,dip:null,lsit:null};for(let w=0;w<52;w++){const d=new Date(mondayOf(new Date()));d.setDate(d.getDate()-w*7);const wd=getWeekData(d);DAYS.forEach(([k],di)=>PROGRAM[k].exercises.forEach((ex,i)=>{const type=classify(ex[0]);if(!type)return;resultValues(wd,k,i).forEach(v=>{if(!rec[type]||v>rec[type].value){const dd=dayDate(di,d);rec[type]={value:v,date:dd,band:type==='muscle'?(wd[extraKey('band',k)]||'Не указана'):''}}})}))}return rec}
function draw(canvas,type){const ctx=canvas.getContext('2d'),ratio=devicePixelRatio||1,w=canvas.clientWidth||300,h=150;canvas.width=w*ratio;canvas.height=h*ratio;ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);const rows=recentWeeks().map(x=>({label:dateLabel(x.date),v:x.m[type]})),positive=rows.filter(x=>x.v>0);if(!positive.length){ctx.fillStyle='#8e959a';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText('Запиши результаты — здесь появится график',w/2,h/2);return}const max=Math.max(...rows.map(x=>x.v),1),pad=18,iw=w-pad*2,ih=h-35;ctx.strokeStyle='#3e454a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad,ih+8);ctx.lineTo(w-pad,ih+8);ctx.stroke();const pts=rows.map((x,i)=>({x:pad+(rows.length===1?iw/2:i*iw/(rows.length-1)),y:8+ih-(x.v/max)*ih,v:x.v}));ctx.strokeStyle='#ffd75c';ctx.lineWidth=2.5;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();pts.forEach(p=>{ctx.fillStyle=p.v?'#ffd75c':'#555b60';ctx.beginPath();ctx.arc(p.x,p.y,3.2,0,Math.PI*2);ctx.fill()});ctx.fillStyle='#899095';ctx.font='9px system-ui';ctx.textAlign='center';[0,2,4,6,7].forEach(i=>{if(rows[i])ctx.fillText(rows[i].label,pts[i].x,h-5)})}
function ensureDashboard(){const week=document.querySelector('.week-section');if(!week||document.getElementById('progressDashboard'))return;const sec=document.createElement('section');sec.id='progressDashboard';sec.className='progress-dashboard';sec.innerHTML=`<div class="progress-head"><div><span class="mini">АНАЛИТИКА</span><h3>Мой прогресс</h3></div></div><div class="progress-grid" id="progressStats"></div><article class="progress-card"><h4>Личные рекорды</h4><div class="record-list" id="recordList"></div></article><article class="progress-card"><h4>График результатов</h4><div class="chart-tabs">${METRICS.map((m,i)=>`<button class="chart-tab${i?'':' active'}" data-metric="${m[0]}">${m[1]}</button>`).join('')}</div><canvas class="progress-chart" id="progressChart"></canvas></article><article class="progress-card"><h4>Статистика недели</h4><div class="week-stats-line" id="weekStats"></div></article>`;week.parentNode.insertBefore(sec,week);sec.querySelectorAll('.chart-tab').forEach(b=>b.onclick=()=>{sec.querySelectorAll('.chart-tab').forEach(x=>x.classList.toggle('active',x===b));draw(document.getElementById('progressChart'),b.dataset.metric)})}
function ensureTools(){const panel=document.querySelector('.workout-panel');if(!panel)return;let tools=panel.querySelector('.workout-tools');if(!tools){tools=document.createElement('div');tools.className='workout-tools';tools.innerHTML=`<div class="band-picker"><span>Резинка для выходов</span><select class="band-select">${BANDS.map(x=>`<option>${x}</option>`).join('')}</select></div><textarea class="workout-note" maxlength="240" placeholder="Заметка о тренировке: техника, самочувствие, что получилось…"></textarea><button class="finish-workout" type="button">✓ Завершить тренировку</button>`;panel.appendChild(tools)}const d=data(),k=selectedDay,band=tools.querySelector('.band-select'),note=tools.querySelector('.workout-note'),btn=tools.querySelector('.finish-workout');band.value=d[extraKey('band',k)]||'Не указана';note.value=d[extraKey('note',k)]||'';const fin=dayFinished(d,k);btn.classList.toggle('finished',fin);btn.textContent=fin?'✓ Тренировка завершена':'✓ Завершить тренировку';band.onchange=()=>{const x=data();x[extraKey('band',k)]=band.value;save(x);refresh()};note.oninput=()=>{const x=data();x[extraKey('note',k)]=note.value;save(x)};btn.onclick=()=>{const x=data();x[extraKey('finished',k)]=!dayFinished(x,k);save(x);if(typeof renderWeek==='function')renderWeek();refresh()}}
function refresh(){ensureDashboard();ensureTools();const d=data(),m=weekMetrics(wk()),prev=new Date(mondayOf(wk()));prev.setDate(prev.getDate()-7);const pm=weekMetrics(prev),rec=records();const stats=document.getElementById('progressStats');if(stats)stats.innerHTML=`<div class="progress-stat"><small>ТРЕНИРОВОК</small><strong>${m.finished}/7</strong><em>${m.finished-pm.finished>=0?'+':''}${m.finished-pm.finished} к прошлой неделе</em></div><div class="progress-stat"><small>ЗАПИСАНО ПОДХОДОВ</small><strong>${m.sets}</strong><em>за выбранную неделю</em></div><div class="progress-stat"><small>ЛУЧШИЙ ВЫХОД</small><strong>${rec.muscle?rec.muscle.value:'—'}</strong><em>${rec.muscle?rec.muscle.band:'нет данных'}</em></div><div class="progress-stat"><small>УГОЛОК</small><strong>${rec.lsit?rec.lsit.value+' сек':'—'}</strong><em>личный рекорд</em></div>`;const rl=document.getElementById('recordList');if(rl)rl.innerHTML=METRICS.map(([type,label])=>{const r=rec[type],unit=type==='lsit'?' сек':' повт.';return`<div class="record-row"><span>${label}</span><b>${r?r.value+unit:'—'}${r?`<small>${dateLabel(r.date)}${type==='muscle'?' · '+r.band:''}</small>`:''}</b></div>`}).join('');const ws=document.getElementById('weekStats');if(ws)ws.textContent=`Выполнено тренировок: ${m.finished} из 7 · Записано подходов: ${m.sets} · Изменение к прошлой неделе: ${m.finished-pm.finished>=0?'+':''}${m.finished-pm.finished} тренировок.`;const active=document.querySelector('.chart-tab.active');const canvas=document.getElementById('progressChart');if(canvas)draw(canvas,active?.dataset.metric||'muscle')}
if(typeof renderWeek==='function'){const base=renderWeek;renderWeek=function(...a){const r=base.apply(this,a);setTimeout(refresh,0);return r}}
setTimeout(refresh,0);window.addEventListener('resize',()=>{const c=document.getElementById('progressChart'),a=document.querySelector('.chart-tab.active');if(c)draw(c,a?.dataset.metric||'muscle')});
})();